# Workflow to build and publish feature/fix branches

name: Build on feature/fix branch

# Run on manual trigger only
on:
  workflow_call:
    inputs:
      do_pack:
        description: 'If this build should be packed as NuGet package.'
        required: true
        type: boolean

jobs:
  get-feature-branch:
  
    runs-on: ubuntu-latest
    outputs:
      branch_name: ${{ steps.normalize.outputs.branch_name }}
    
    steps:
    - uses: actions/checkout@v3
    
    # Remove feature/fix branch prefix, hyphens etc. and trim to 20 characters
    - name: Normalize branch name
      run: |
        branch="${{ github.ref_name }}"
        noSlashes=`echo $branch | sed "s/[^[:alnum:]]//g"`
        noFeature="${noSlashes/feature/}"
        noFix="${noFeature/fix/}"
        echo "::set-output name=branch_name::$( echo $noFix | cut -c 1-20 )"
      id: normalize

  feature-branch:
    needs: get-feature-branch
    uses: ./.github/workflows/build-and-pack.yml
    with:
      configuration: "Debug"
      is_prerelease: true
      do_pack: ${{ inputs.do_pack }}
      suffix: "alpha-${{ needs.get-feature-branch.outputs.branch_name }}"
      publish_target: "None"
    secrets: inherit
